[package]
name = "translatabase"
version = "0.1.0"
authors = ["Jonathan Sharman <jonathan.sharman@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
rocket = "0.4.6"
rocket_contrib = "0.4.6"
webbrowser = "0.5.5"

[dependencies.rusqlite]
version = "0.24.2"
features = ["bundled"]
